sudo: required
dist: trusty
language: node_js
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: "ppa:wine/wine-builds"
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
    - wine
env: CXX=g++-4.8
before_script:
- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
- mkdir "$ANDROID_HOME/licenses"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm run apply:copay
- export OUTDIR=$HOME/outputs
- mkdir $OUTDIR
script:
- pwd
- npm run build:desktop
- if [ "$TRAVIS_TAG" != "" ]; then wineboot;npm run build:windows-exe; fi
- ls -al $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/webkitbuilds
- if [ -f $TRAVIS_BUILD_DIR/webkitbuilds/InstaDEX\ Copay.exe ]; then
  cp $TRAVIS_BUILD_DIR/webkitbuilds/InstaDEX\ Copay.exe $OUTDIR/instadex-copay-win64-setup.exe;
  fi
- cd $TRAVIS_BUILD_DIR/webkitbuilds/InstaDEX\ Copay/
- zip -r $OUTDIR/instadex-copay.win64.zip win64/*
- cd $TRAVIS_BUILD_DIR/webkitbuilds/InstaDEX\ Copay/
- zip -r $OUTDIR/instadex-copay.linux64.zip linux64/*
- cd $TRAVIS_BUILD_DIR/webkitbuilds/InstaDEX\ Copay/osx64
- zip -r $OUTDIR/instadex-copay.osx64.zip InstaDEX\ Copay.app
- cd $OUTDIR
- touch $OUTDIR/sha256sums.txt
- if [ -f instadex-copay-win64-setup.exe ]; then sha256sum instadex-copay-win64-setup.exe >>
  $OUTDIR/sha256sums.txt;if [ "$TRAVIS_TAG" == "" ]; then travis_retry curl --max-time 60 --upload
  $OUTDIR/instadex-copay-win64-setup.exe https://transfer.sh/; fi;fi
- if [ -f instadex-copay.win64.zip ]; then sha256sum instadex-copay.win64.zip >>
  $OUTDIR/sha256sums.txt;if [ "$TRAVIS_TAG" == "" ];then travis_retry curl --max-time 60 --upload
  $OUTDIR/instadex-copay.win64.zip https://transfer.sh/; fi;fi
- if [ -f instadex-copay.linux64.zip ]; then sha256sum instadex-copay.linux64.zip >>
  $OUTDIR/sha256sums.txt;if [ "$TRAVIS_TAG" == "" ];then travis_retry curl --max-time 60 --upload
  $OUTDIR/instadex-copay.linux64.zip https://transfer.sh/; fi;fi
- if [ -f instadex-copay.osx64.zip ]; then sha256sum instadex-copay.osx64.zip >>
  $OUTDIR/sha256sums.txt;if [ "$TRAVIS_TAG" == "" ];then travis_retry curl --max-time 60 --upload
  $OUTDIR/instadex-copay.osx64.zip https://transfer.sh/; fi;fi
- cat $OUTDIR/sha256sums.txt
- cd $TRAVIS_BUILD_DIR
- npm run final:www && npm run build:android-release
- cp ~/build/instadex/copay/platforms/android/build/outputs/apk/android-release-unsigned.apk
  $OUTDIR/
- cd $OUTDIR
- if [ -f android-release-unsigned.apk ]; then
  sha256sum android-release-unsigned.apk >>
  sha256sums.txt;if [ "$TRAVIS_TAG" == "" ];then travis_retry curl --max-time 20 --upload
  $OUTDIR/android-release-unsigned.apk https://transfer.sh/; fi;fi
- cat $OUTDIR/sha256sums.txt
deploy:
  provider: releases
  api_key:
    secure: SKFkIeqJEgcQGCyvvw72VXM6sIKoCRjz/0B0rInZHMy5qQAXsyVEZVvjkSN25eh4MqJThuA+bM+NPtMZWOML3vxNz/5eEEn0c3QeQan6tx3ab5RYJEYq7ESnZe36ihysPjYvPNBZiSzNlpz70oCbZ5xEGQSAQQ2h6sc9Ql6yp7f3Al5gsdoVExvN7ziLWe2elZw0v/LREZjTOXeUP9QdW65uGSy20Gigpv7LRGZy80F9IqiOKlsGX30gaupkw28hQck6A978LkTr/zp9BMIREl9vFZItw0rraMQnYRtpA5caxRSJM/9DZVolJFAAGN9BeyGblwHHeb7CJJ7Yon126fVMmiAP+HdpAdWJIGtUEYCbqQ0ai5B14pzv9WF5fx83zfsPZ07N+YzUpvPJOiMLZtuwrn9y+Lqq+HCnshaqJ+6Fd2GBWbFwDpqeOophN4CvgXfA33Mp91HGmGi/oD/qvstWFPgCEBvZghSYnoEnYUJVpMR3UOYHPqCtRnuA6+zwT89n0oQol6hRqDtYGi5JGShEDligE1+rBytOAHvY7OZVOZv/zy7vB5t2oFvyGnjBL1jsXqaF3WxzrSbvCSc7hJ3ITfM5QKaKxxavGAARpZVArPZxTN4HWK4j4Y4h15GI8yaFz2MVcWY1SFfQnphzkPWWtG6M8qk0nlWGfHm2mGE=
  file: # Linter thinks this is broken?
    - $OUTDIR/instadex-copay.win64.zip
    - $OUTDIR/instadex-copay-win64-setup.exe
    - $OUTDIR/instadex-copay.linux64.zip
    - $OUTDIR/instadex-copay.osx64.zip
    - $OUTDIR/android-release-unsigned.apk
    - $OUTDIR/sha256sums.txt
  overwrite: true
  on:
    tags: true
